USE Minions

DROP TABLE Users

/*   CREATE TABLE  */
USE Minions
CREATE TABLE Users(
Id BIGINT IDENTITY NOT NULL,
Username VARCHAR(30) UNIQUE NOT NULL,
Password  VARCHAR(26) NOT NULL,
ProfilePicture VARBINARY(MAX),
LastLoginTime DATETIME,
IsDeleted BIT 
CONSTRAINT PK_Users PRIMARY KEY (Id)
)

ALTER TABLE Users
DROP CONSTRAINT PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (id, Username)


SELECT * FROM Users