// <auto-generated />
using L01.Cars.Data;
using L01.Cars.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace L01.Cars.Data.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("L01.Cars.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Doors");

                    b.Property<int>("EngineId");

                    b.Property<int?>("LicensePlateId");

                    b.Property<int>("MakeId");

                    b.Property<string>("Model");

                    b.Property<DateTime>("ProductionYear");

                    b.Property<int>("Transmission");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("MakeId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.CarDealership", b =>
                {
                    b.Property<int>("CarId");

                    b.Property<int>("DealershipId");

                    b.HasKey("CarId", "DealershipId");

                    b.HasIndex("DealershipId");

                    b.ToTable("CarDealerships");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.Dealership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Capacity");

                    b.Property<int>("Cyllinders");

                    b.Property<int>("FuelType");

                    b.Property<int>("HorsePower");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.LicensePlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique()
                        .HasFilter("[CarId] IS NOT NULL");

                    b.ToTable("LicensePlates");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("L01.Cars.Data.Models.Car", b =>
                {
                    b.HasOne("L01.Cars.Data.Models.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("L01.Cars.Data.Models.Make", "Make")
                        .WithMany("Cars")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("L01.Cars.Data.Models.CarDealership", b =>
                {
                    b.HasOne("L01.Cars.Data.Models.Car", "Car")
                        .WithMany("CarsDealerships")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("L01.Cars.Data.Models.Dealership", "Dealership")
                        .WithMany("CarsDealerships")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("L01.Cars.Data.Models.LicensePlate", b =>
                {
                    b.HasOne("L01.Cars.Data.Models.Car", "Car")
                        .WithOne("LicensePlate")
                        .HasForeignKey("L01.Cars.Data.Models.LicensePlate", "CarId");
                });
#pragma warning restore 612, 618
        }
    }
}
